
load in the database in the database
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)

rawtemp = read.table("/Users/machaango/OneDrive/Desktop/thesis/zapata_thesis/data/climdiv-tmpcst-v1.0.0-20241021.txt", header = FALSE, colClasses = c("character",rep("numeric",12)))


rawtemp = rawtemp |>
  rename(ID = V1,
         Jan = V2,
         Feb = V3,
         Mar = V4,
         Apr = V5,
         May = V6,
         June = V7,
         July = V8,
         Aug = V9,
         Sept = V10,
         Oct = V11,
         Nov = V12,
         Dec = V13) |>
  mutate(StateID = NA,
         Year = NA) |> 
  relocate(Year, .after = ID) |> 
  relocate(StateID, .after = Year)



```


reformat the columns and parse the ID variable
```{r}

for(i in 1:nrow(rawtemp)){
  id_var = rawtemp$ID[i]
  rawtemp$StateID[i] = substring(id_var, 1, 3)
  rawtemp$Year[i] = substring(id_var, 7, 10)
}
rm(id_var)
rm(i)

cleaned = rawtemp
rm(rawtemp)
cleaned$Year = as.integer(cleaned$Year)
cleaned$StateID = as.integer(cleaned$StateID)

```


start filtering out
- years below the correct date-- to match NORS, we will drop all before 1998
- additionally, missing data is entered in as -99.90 (per the readme)
- so those become NA


```{r}
#12614 observations as of right now
cleaned_regions = cleaned |> 
  filter(StateID <= 109 & StateID >= 101) |>
  filter(Year >= 1998 & Year <= 2019)

#no NA values in this subsection. reduced down to 198 obs w/these filters
# 9 regions x 22 year period = 198 observations so we're good

cleaned_states = cleaned |> 
  filter(StateID <= 48) |> 
  filter(Year >= 1998 & Year <= 2019)
# 48 states x 22 year period = 1056 observations so all good

cleaned_regions2 = cleaned |> 
  filter(StateID <= 109 & StateID >= 101) |> 
  filter(Year != 2024)

write.csv(cleaned_regions2, "data/NOAA_regions_allyears.csv", row.names = FALSE)
write.csv(cleaned_regions, "data/NOAA_regions.csv", row.names = FALSE)
write.csv(cleaned_states, "data/NOAA_states.csv", row.names = FALSE)

rm(cleaned)
rm(cleaned_regions)
rm(cleaned_states)
rm(cleaned_regions2)

```