


```{r}

library(dplyr)
library(ggplot2)
library(tidyverse)

NORS = read.csv("/Users/machaango/OneDrive/Desktop/thesis/zapata_thesis/data/refined.csv", header = TRUE)

```



Distribution of observations
```{r}
#by year
year_counts = NORS |> group_by(Year) |> 
  summarize(n = n())

year_hist = NORS |> group_by(Year) |> 
  summarize(n = n()) |> 
  ggplot(aes(Year))+
  geom_histogram(aes(weight = n))


#by state
state_counts = NORS |> group_by(State) |> 
  summarize(n = n())

#state_graph = NORS |> group_by(Year) |> 
#  summarize(n = n()) |> 
#  ggplot(aes(Year))+
#  geom_histogram(aes(weight = n))


#diseases

#refined |>  
#  group_by(Setting) |> 
#  summarize(n = n())

#refined |> group_by(Year) |> 
#  summarize(n = n())



#tbh i'm not even sure how to go about cleaning this
#what even are relevant categories to divide by?

```



exploring lists (and counts) of each unique etiology entry to prep for pruning
```{r}

single_factors = refined |>  
  filter(!is.na(Etiology)) |> 
  filter(Etiology != "Multiple")|> 
  group_by(Etiology) |> 
  summarize(n = n())

single_factors
#listed_factors = refined |> 
#  filter(Etiology == "Multiple") |> 
#  group_by(Etiology.Expanded) |> 
#  summarize(n = n())

write.csv(single_factors, "etiologies_single.csv")
#write.csv(listed_factors, "listed_factors.csv")

```


```

