```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)


tem = read.csv("/Users/machaango/OneDrive/Desktop/thesis/zapata_thesis/data/tempdata/temp_reg.csv", header = TRUE)
hum = read.csv("/Users/machaango/OneDrive/Desktop/thesis/zapata_thesis/data/humdata/hum_reg.csv", header = TRUE)
NORS = read.csv("/Users/machaango/OneDrive/Desktop/thesis/zapata_thesis/data/NORS_refined.csv", header = TRUE)

```
custom month/date function
```{r}
numMonth = function(df){
  for (i in 1:nrow(df)){ 
    temp = df$Month[i]
    if(temp == "Jan"){
      df$Month[i] = 1
      }
    else if(temp == "Feb"){
      df$Month[i] = 2
      }
    else if(temp == "Mar"){
      df$Month[i] = 3
      }
    else if(temp == "Apr"){
      df$Month[i] = 4
      }
    else if(temp == "May"){
      df$Month[i] = 5
      }
    else if(temp == "June"){
      df$Month[i] = 6
      }
    else if(temp == "July"){
      df$Month[i] = 7
      }
    else if(temp == "Aug"){
      df$Month[i] = 8
      }
    else if(temp == "Sept"){
      df$Month[i] = 9
      }
    else if(temp == "Oct"){
      df$Month[i] = 10
      }
    else if(temp == "Nov"){
      df$Month[i] = 11
      }
    else if(temp == "Dec"){
      df$Month[i] = 12
      }
    }
  
  rm(i, temp)
  df$Month = as.integer(df$Month)
  df$Region = as.factor(df$Region)
  
  df = df |> mutate(Date2 = as.Date(paste(Year, Month, "01", sep = "-")))

  return(df)
  }

```


#pivot and vectorization (change variables)
```{r}
target = "Temperature"
if (target == "Humidity"){
  piv = hum
} else if (target == "Temperature"){
  piv = tem 
} else {
  stop("change top line of code!")
  }

piv = piv |>
  pivot_longer(
    cols = !(c(ID, Region, Year)),
    names_to = "Month",
    values_to = target
  ) |> 
  select(!("ID"))
piv = numMonth(piv)

if (target == "Humidity"){
  vec = piv |> 
  group_by(Region) |> 
  summarize(
    Humidity = list(Humidity))
  hum_piv = piv
  hum_vec = vec
} else if (target == "Temperature"){
  vec = piv |> 
  group_by(Region) |> 
  summarize(
    Temperature = list(Temperature)) 
  temp_piv = piv
  temp_vec = vec
}

rm(piv)
rm(vec)
rm(target)
```

deconstructing (visual time series)
```{r}
regions_list = c("Northeast","East North Central", "Central", "Southeast", "West North Central", "South", "Southwest", "Northwest", "West Region")

for (i in 1:nrow(temp_vec)){
  temp = unlist(temp_vec$Temperature[i])
  tempts = ts(temp, frequency = 12, start = 1998)
  plot(decompose(tempts))
  axis(1, at = seq(1998, 2020, by = 2))
  title(temp_vec$Region[i])
  ##title these for our own sanity
  }

#test = unlist(temp_vec$Temperature[3])
#tempts = ts(test, frequency = 12, start = 1998)
#plot.ts(tempts)
#plot(decompose(tempts))
#axis(1, at = seq(1998, 2020, by = 2))



#plot.ts(SMA(tempts, n = 12))

```


```{r}
NORS |> ggplot(aes(x = Region, fill = Etiology))+
  geom_bar(position = "fill")


NORS |> group_by(Etiology) |> count() |> arrange(desc(n))

```

```{r}
chitest1 = NORS |> 
  group_by(Region, Etiology) |> 
  count() |> 
  pivot_wider(names_from = Region, values_from = n, values_fill = 0)

chitest2 = chitest1 |> ungroup() |> select(!(Etiology))
chisq.test(chitest2)





```

